// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLeK19C6yNOAnXPR6C7Z9ELXPf65ik4y8',
    appId: '1:356307840908:web:ac7e2ed0d331b3e8bab0a9',
    messagingSenderId: '356307840908',
    projectId: 'flutter-firebase-11',
    authDomain: 'flutter-firebase-11.firebaseapp.com',
    storageBucket: 'flutter-firebase-11.appspot.com',
    measurementId: 'G-H8P8GRTZHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPQTRXJSvVloSVH4OBTEBBGwIuEVvzA1Y',
    appId: '1:356307840908:android:749833205e2f63d1bab0a9',
    messagingSenderId: '356307840908',
    projectId: 'flutter-firebase-11',
    storageBucket: 'flutter-firebase-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZgkOun4cqAtyDTvNpQPatGDIhQy5L24',
    appId: '1:356307840908:ios:1de7f3ee18966bf0bab0a9',
    messagingSenderId: '356307840908',
    projectId: 'flutter-firebase-11',
    storageBucket: 'flutter-firebase-11.appspot.com',
    iosBundleId: 'com.example.weAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkZgkOun4cqAtyDTvNpQPatGDIhQy5L24',
    appId: '1:356307840908:ios:1de7f3ee18966bf0bab0a9',
    messagingSenderId: '356307840908',
    projectId: 'flutter-firebase-11',
    storageBucket: 'flutter-firebase-11.appspot.com',
    iosBundleId: 'com.example.weAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLeK19C6yNOAnXPR6C7Z9ELXPf65ik4y8',
    appId: '1:356307840908:web:ceec5a742acaeae2bab0a9',
    messagingSenderId: '356307840908',
    projectId: 'flutter-firebase-11',
    authDomain: 'flutter-firebase-11.firebaseapp.com',
    storageBucket: 'flutter-firebase-11.appspot.com',
    measurementId: 'G-YDS51EEDV2',
  );
}
